---

- name: Install packages
  apt:
    name: "{{ item }}"
  with_items: "{{ pi_bootstrap_packages }}"

- name: Install gems
  gem:
    name: "{{ item }}"
  with_items: "{{ pi_bootstrap_packages_gems }}"

- name: Install pips
  pip:
    name: "{{ item }}"
  with_items: "{{ pi_bootstrap_packages_pips }}"
