---

- name: install packages
  apt:
    name: "{{ item }}"
  with_items: "{{ pi_bootstrap_packages }}"

- name: install gems
  gem:
    name: "{{ item }}"
  with_items: "{{ pi_bootstrap_packages_gems }}"
